name: CI

on:
  push:
    branches: [main]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f .requirements.txt ]; then pip install -r .requirements.txt; fi
      
      - name: Run flake8
        run: flake8 --verbose .

  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install black
        run: |
          python -m pip install --upgrade pip
          pip install black
          if [ -f .requirements.txt ]; then pip install -r .requirements.txt; fi
      
      - name: Run black check
        run: black --check --diff .
